version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
   container_name: elasticsearch
   ports:
     - "9200:9200"
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
     
  kibana:
   image: docker.elastic.co/kibana/kibana:7.5.1
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
     - "27017:27017"